ta# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           none

# Setup
title:               California Pay Equity Task Force Interim Report
tagline:             'April 2017'
description:        'Prepared for the Pay Equity Task Force<br /> by the California Commission on the Status of Women and Girls.'
url:                http://women.ca.gov/interimreport
baseurl:             'https://tdlindsey.github.io/opendata-1/'
paginate:            5

# About/contact
author:
  name:              California Commission on the Status of Women and Girls
  url:               http://women.ca.gov/
  email:             women@women.ca.gov

# Custom vars
version:             1.0
github:
  repo:         https://github.com/TDLindsey/opendata-1
