# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           none

# Setup
title:               Making Open Data Work in California's State Government
tagline:             'Lessons from Early Adopters'
description:         'Prepared for the California State Library<br /> by the California Research Bureau.'
url:                 http://library.ca.gov/crb/opendatarefbook
baseurl:             'http://castatelibrary.github.io/opendata'
paginate:            5

# Setup
title:               California Pay Equity Task Force Interim Report
tagline:             'April 2017'
description:        'Prepared by the<br /> California Commission on the Status of Women and Girls.'
url:                http://women.ca.gov/interimreport
baseurl:             'https://tdlindsey.github.io/opendata-1/'
paginate:            5

# About/contact
author:
  name:              California Commission on the Status of Women and Girls
  url:               http://women.ca.gov/
  email:             women@women.ca.gov

# Custom vars
version:             1.0
github:
  repo:         https://github.com/TDLindsey/opendata-1
